//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIPReference.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbiip")]
        public string UserId1 {
            get {
                return ((string)(this["UserId1"]));
            }
            set {
                this["UserId1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataSource2 {
            get {
                return ((string)(this["DataSource2"]));
            }
            set {
                this["DataSource2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialCatalog1 {
            get {
                return ((string)(this["InitialCatalog1"]));
            }
            set {
                this["InitialCatalog1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbiip")]
        public string Password1 {
            get {
                return ((string)(this["Password1"]));
            }
            set {
                this["Password1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialCatalog2 {
            get {
                return ((string)(this["InitialCatalog2"]));
            }
            set {
                this["InitialCatalog2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserId2 {
            get {
                return ((string)(this["UserId2"]));
            }
            set {
                this["UserId2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password2 {
            get {
                return ((string)(this["Password2"]));
            }
            set {
                this["Password2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsVisibleINVENTORY {
            get {
                return ((bool)(this["IsVisibleINVENTORY"]));
            }
            set {
                this["IsVisibleINVENTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsVisibleNORMAL {
            get {
                return ((bool)(this["IsVisibleNORMAL"]));
            }
            set {
                this["IsVisibleNORMAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsVisibleADDITION {
            get {
                return ((bool)(this["IsVisibleADDITION"]));
            }
            set {
                this["IsVisibleADDITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsVisibleTOTAL {
            get {
                return ((bool)(this["IsVisibleTOTAL"]));
            }
            set {
                this["IsVisibleTOTAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsVisibleINCLEARING {
            get {
                return ((bool)(this["IsVisibleINCLEARING"]));
            }
            set {
                this["IsVisibleINCLEARING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string opedate {
            get {
                return ((string)(this["opedate"]));
            }
            set {
                this["opedate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\fqctge08\e$\NCR_Dev\NCR\NCBDEV\OCRFoundation\Bin\LOG</string>
  <string>\\fqctge01\e$\NCR_Dev\NCR\NCBDEV\OCRFoundation\Bin\LOG</string>
  <string>\\fqctge04\e$\NCR_Dev\NCR\NCBDEV\OCRFoundation\Bin\LOG</string>
  <string>\\fqctge11\e$\NCR_Dev\NCR\NCBDEV\OCRFoundation\Bin\LOG</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ErrLogFolderPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ErrLogFolderPath"]));
            }
            set {
                this["ErrLogFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bofdev")]
        public string DataSource1 {
            get {
                return ((string)(this["DataSource1"]));
            }
            set {
                this["DataSource1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("【BOF】開発環境")]
        public string DISPENV {
            get {
                return ((string)(this["DISPENV"]));
            }
            set {
                this["DISPENV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172_20_0_100|172_20_0_101|10_98_180_180|10_98_180_183")]
        public string OcrFoundationTerm {
            get {
                return ((string)(this["OcrFoundationTerm"]));
            }
            set {
                this["OcrFoundationTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1号機|2号機|3号機|4号機")]
        public string OcrFoundationGoki {
            get {
                return ((string)(this["OcrFoundationGoki"]));
            }
            set {
                this["OcrFoundationGoki"] = value;
            }
        }
    }
}
