DROP TABLE dbctr.TERM_LOCK;
CREATE TABLE dbctr.TERM_LOCK (
    LASTIPADDRESS number(1,0) NOT NULL,
    CREATE_DATE number(8,0) default 0 ,
    CREATE_TIME number(9,0) default 0 ,
CONSTRAINT PK_DBCTR_TERM_LOCK PRIMARY KEY (
     LASTIPADDRESS
));

COMMENT ON TABLE dbctr.TERM_LOCK IS '取扱端末ロック';
COMMENT ON COLUMN dbctr.TERM_LOCK.LASTIPADDRESS IS 'IPアドレス最終値';
COMMENT ON COLUMN dbctr.TERM_LOCK.CREATE_DATE IS '作成日付';
COMMENT ON COLUMN dbctr.TERM_LOCK.CREATE_TIME IS '作成時刻';
exit;