DROP TABLE dbctr.WK_IMGELIST;
CREATE TABLE dbctr.WK_IMGELIST (
    SEARCH_TERMID varchar2(20) NOT NULL,
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    SCAN_TERM varchar2(20) NOT NULL,
    BAT_ID number(6,0) NOT NULL,
    DETAILS_NO number(6,0) NOT NULL,
    SORT_NO number(6,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR_WK_IMGELIST PRIMARY KEY (
     SEARCH_TERMID
    ,GYM_ID
    ,OPERATION_DATE
    ,SCAN_TERM
    ,BAT_ID
    ,DETAILS_NO
));
COMMENT ON TABLE dbctr.WK_IMGELIST IS '明細イメージリスト';
COMMENT ON COLUMN dbctr.WK_IMGELIST.SEARCH_TERMID IS '一覧表示端末:IPアドレス（.→_に変換）';
COMMENT ON COLUMN dbctr.WK_IMGELIST.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr.WK_IMGELIST.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr.WK_IMGELIST.SCAN_TERM IS 'イメージ取込端末:IPアドレス（.→_に変換）';
COMMENT ON COLUMN dbctr.WK_IMGELIST.BAT_ID IS 'バッチ番号';
COMMENT ON COLUMN dbctr.WK_IMGELIST.DETAILS_NO IS '明細番号';
COMMENT ON COLUMN dbctr.WK_IMGELIST.SORT_NO IS 'ソート順';
exit;