DROP TABLE dbctr.ERA;
CREATE TABLE dbctr.ERA (
    SEQ number(2,0) NOT NULL,
    KANJI varchar2(4) NOT NULL,
    SHORTKANJI varchar2(2) NOT NULL,
    ROMAN varchar2(10) NOT NULL,
    SHORTROMAN varchar2(2) NOT NULL,
    TOWAREKIYEAR number(4,0) NOT NULL,
    STARTDATE number(8,0) NOT NULL,
    ENDDATE number(8,0) NOT NULL,
 CONSTRAINT PK_DBCTR_ERA PRIMARY KEY (
     SEQ
));
COMMENT ON TABLE dbctr.ERA IS '元号マスタ';
COMMENT ON COLUMN dbctr.ERA.SEQ IS '番号';
COMMENT ON COLUMN dbctr.ERA.KANJI IS '元号名称';
COMMENT ON COLUMN dbctr.ERA.SHORTKANJI IS '元号略称';
COMMENT ON COLUMN dbctr.ERA.ROMAN IS '元号ローマ名称';
COMMENT ON COLUMN dbctr.ERA.SHORTROMAN IS '元号ローマ略称';
COMMENT ON COLUMN dbctr.ERA.TOWAREKIYEAR IS '西暦';
COMMENT ON COLUMN dbctr.ERA.STARTDATE IS '開始日付';
COMMENT ON COLUMN dbctr.ERA.ENDDATE IS '終了日付';
exit;