DROP TABLE dbctr9999.TRBATCH_HIST;
CREATE TABLE dbctr9999.TRBATCH_HIST (
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    SCAN_TERM varchar(20) NOT NULL,
    BAT_ID number(6,0) NOT NULL,
    SEQ number(3,0) NOT NULL,
    STS number(2) default 0  NOT NULL,
    INPUT_ROUTE number(1,0) default 0  NOT NULL,
    OC_BK_NO number(4,0) default -1  NOT NULL,
    OC_BR_NO number(4,0) default -1  NOT NULL,
    SCAN_BR_NO number(4,0) default -1  NOT NULL,
    SCAN_DATE number(8,0) default 0  NOT NULL,
    CLEARING_DATE number(8,0) default 0  NOT NULL,
    SCAN_COUNT number(6,0) default 0  NOT NULL,
    TOTAL_COUNT number(6,0) default 0  NOT NULL,
    TOTAL_AMOUNT number(18,0) default 0  NOT NULL,
    DELETE_DATE number(8,0) default 0  NOT NULL,
    DELETE_FLG number(1,0) default 0  NOT NULL,
    E_TERM varchar(20),
    E_OPENO varchar(20),
    E_YMD number(8,0) default 0  NOT NULL,
    E_TIME number(11,0) default 0  NOT NULL,
    UPDATE_DATE number(8,0) default 0  NOT NULL,
    UPDATE_TIME number(11,0) default 0  NOT NULL,
    UPDATE_KBN number(1,0) default 1  NOT NULL,
 CONSTRAINT PK_DBCTR9999_TRBATCH_HIST PRIMARY KEY (
     GYM_ID
    ,OPERATION_DATE
    ,SCAN_TERM
    ,BAT_ID
    ,SEQ
));
COMMENT ON TABLE dbctr9999.TRBATCH_HIST IS 'バッチデータ履歴';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.SCAN_TERM IS 'イメージ取込端末';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.BAT_ID IS 'バッチ番号';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.SEQ IS '出力連番';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.STS IS '状態';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.INPUT_ROUTE IS '取込ルート';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.OC_BK_NO IS '持出銀行（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.OC_BR_NO IS '持出支店（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.SCAN_BR_NO IS 'スキャン支店（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.SCAN_DATE IS 'スキャン日（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.CLEARING_DATE IS '交換希望日（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.SCAN_COUNT IS 'スキャン枚数（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.TOTAL_COUNT IS '合計枚数（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.TOTAL_AMOUNT IS '合計金額（持出バッチ票値）';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.DELETE_DATE IS '削除日';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.DELETE_FLG IS '削除フラグ';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.E_TERM IS 'バッチ票入力端末';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.E_OPENO IS 'バッチ票入力オペレーター番号';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.E_YMD IS 'バッチ票入力日付';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.E_TIME IS 'バッチ票入力時間';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.UPDATE_DATE IS '更新日:更新システム日付';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.UPDATE_TIME IS '更新時間:更新システム時刻';
COMMENT ON COLUMN dbctr9999.TRBATCH_HIST.UPDATE_KBN IS '更新区分:1：新規登録 2：アップデート';
exit;