DROP TABLE dbctr9999.IMG_CURSOR_PARAM;
CREATE TABLE dbctr9999.IMG_CURSOR_PARAM (
    GYM_ID NUMBER(3,0) NOT NULL,
    DSP_ID NUMBER(3,0) NOT NULL,
    ITEM_ID NUMBER(3,0) NOT NULL,
    ITEM_TOP NUMBER(10,1) default 0  NOT NULL,
    ITEM_LEFT NUMBER(10,1) default 0  NOT NULL,
    ITEM_WIDTH NUMBER(10,1) default 0  NOT NULL,
    ITEM_HEIGHT NUMBER(10,1) default 0  NOT NULL,
    LINE_WEIGHT NUMBER(10,1) default 0  NOT NULL,
    LINE_COLOR NUMBER(10,1) default 0  NOT NULL,
CONSTRAINT PK_DBCTR9999_IMG_CURSOR_PARAM PRIMARY KEY (
     GYM_ID
    ,DSP_ID
    ,ITEM_ID
));
COMMENT ON TABLE dbctr9999.IMG_CURSOR_PARAM IS 'イメージカーソルパラメータ';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.ITEM_ID IS '項目ID';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.ITEM_TOP IS 'TOP項目位置';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.ITEM_LEFT IS 'LEFT項目位置';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.ITEM_WIDTH IS 'WIDTH項目位置';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.ITEM_HEIGHT IS 'HEIGHT項目位置';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.LINE_WEIGHT IS '罫線太さ';
COMMENT ON COLUMN dbctr9999.IMG_CURSOR_PARAM.LINE_COLOR IS '罫線色';
exit;