DROP TABLE dbctr.BKCHANGEMF;
CREATE TABLE dbctr.BKCHANGEMF (
    OLD_BK_NO number(4,0) NOT NULL,
    NEW_BK_NO number(4,0) default -1  NOT NULL,
    DESCRIPTION varchar2(100),
CONSTRAINT PK_DBCTR_BKCHANGEMF PRIMARY KEY (
     OLD_BK_NO
));
COMMENT ON TABLE dbctr.BKCHANGEMF IS '銀行読替マスタ';
COMMENT ON COLUMN dbctr.BKCHANGEMF.OLD_BK_NO IS '旧銀行番号';
COMMENT ON COLUMN dbctr.BKCHANGEMF.NEW_BK_NO IS '新銀行番号';
COMMENT ON COLUMN dbctr.BKCHANGEMF.DESCRIPTION IS '備考';
exit;