DROP TABLE dbctr9999.DSP_ITEM;
CREATE TABLE dbctr9999.DSP_ITEM (
    GYM_ID NUMBER(3,0) NOT NULL,
    DSP_ID NUMBER(3,0) NOT NULL,
    ITEM_ID NUMBER(3,0) NOT NULL,
    ITEM_DISPNAME VARCHAR2(40),
    ITEM_TYPE VARCHAR2(1),
    ITEM_LEN NUMBER(2,0) default 0  NOT NULL,
    POS NUMBER(4,0) default 0  NOT NULL,
    DUP VARCHAR2(1),
    AUTO_INPUT VARCHAR2(1),
    ITEM_SUBRTN VARCHAR2(150),
    BLANK_FLG VARCHAR2(1),
CONSTRAINT PK_DBCTR9999_DSP_ITEM PRIMARY KEY (
     GYM_ID
    ,DSP_ID
    ,ITEM_ID
));
COMMENT ON TABLE dbctr9999.DSP_ITEM IS '画面項目定義';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.ITEM_ID IS '項目番号';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.ITEM_DISPNAME IS '項目表示名称';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.ITEM_TYPE IS '項目タイプ';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.ITEM_LEN IS '項目文字長';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.POS IS '外部連携ファイル項目位置:バイナリデータ開始位置';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.DUP IS 'DUP有無:0：DUP不可 1：DUP可';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.AUTO_INPUT IS '項目フル桁入力次項目遷移:0：しない 1：する';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.ITEM_SUBRTN IS 'サブルーチン';
COMMENT ON COLUMN dbctr9999.DSP_ITEM.BLANK_FLG IS '空白フラグ';
exit;