DROP TABLE dbctr.OPERATOR;
CREATE TABLE dbctr.OPERATOR (
    OPENO varchar2(20) NOT NULL,
    OPENAME varchar2(30),
    AUTH number(2,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR_OPERATOR PRIMARY KEY (
     OPENO
));
COMMENT ON TABLE dbctr.OPERATOR IS 'オペレータマスタ';
COMMENT ON COLUMN dbctr.OPERATOR.OPENO IS 'オペレータID:VARCHAR2(20)';
COMMENT ON COLUMN dbctr.OPERATOR.OPENAME IS 'オペレータ名称:VARCHAR2(30)';
COMMENT ON COLUMN dbctr.OPERATOR.AUTH IS '権限:NUMBER(2, 0)';
exit;