DROP TABLE dbctr9999.BATCH_SEQ;
CREATE TABLE dbctr9999.BATCH_SEQ (
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    LAST_SEQ number(8,0) default 0 ,
    LAST_SEQ_DATE number(8,0) default 0 ,
    LAST_SEQ_TIME number(9,0) default 0 ,
    LAST_FILE_ID varchar2(5),
    LAST_FILE_DIVID varchar2(3),
CONSTRAINT PK_DBCTR9999_BATCH_SEQ PRIMARY KEY (
     GYM_ID
    ,OPERATION_DATE
));

COMMENT ON TABLE dbctr9999.BATCH_SEQ IS 'バッチ番号採番';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.LAST_SEQ IS '最終一連番号:0：初期値 使用時に使用番号にカウントアップ 日初時に0クリアする';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.LAST_SEQ_DATE IS '最終採番日付';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.LAST_SEQ_TIME IS '最終採番時刻';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.LAST_FILE_ID IS '最終採番ファイルID';
COMMENT ON COLUMN dbctr9999.BATCH_SEQ.LAST_FILE_DIVID IS '最終採番ファイル識別区分';
exit;