DROP TABLE dbctr9999.HOSEI_STATUS;
CREATE TABLE dbctr9999.HOSEI_STATUS (
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    SCAN_TERM varchar2(20) NOT NULL,
    BAT_ID number(6,0) NOT NULL,
    DETAILS_NO number(6,0) NOT NULL,
    HOSEI_INPTMODE number(1,0) NOT NULL,
    INPT_STS number(4,0) NOT NULL,
    TMNO varchar2(20),
    OPENO varchar2(20),
    E_OPENO varchar2(20),
CONSTRAINT PK_DBCTR9999_HOSEI_STATUS PRIMARY KEY (
     GYM_ID
    ,OPERATION_DATE
    ,SCAN_TERM
    ,BAT_ID
    ,DETAILS_NO
    ,HOSEI_INPTMODE
));
COMMENT ON TABLE dbctr9999.HOSEI_STATUS IS '補正ステータス';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.SCAN_TERM IS 'イメージ取込端末';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.BAT_ID IS 'バッチ番号';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.DETAILS_NO IS '明細番号';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.HOSEI_INPTMODE IS '補正入力モード:1：持帰銀行 2：交換希望日 3：金額 4：自行情報 5：交換尻';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.INPT_STS IS '補正状態:1000：エントリ待 1001：エントリ中 1005：エントリ保留 2000：ベリファイ待 2001：ベリファイ中 2005：ベリファイ保留 3000：完了 3001：完了訂正中 3005：完了訂正保留 4001：持出エラー訂正中 4005：持出エラー訂正保留';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.TMNO IS '端末番号';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.OPENO IS 'オペレーター番号';
COMMENT ON COLUMN dbctr9999.HOSEI_STATUS.E_OPENO IS 'エントリーオペレーター番号';
exit;