--------------------------------------------------------
--  DDL for Trigger TRMEIIMG_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DBCTR9999"."TRMEIIMG_LOG_TRG" AFTER
    INSERT OR UPDATE ON DBCTR9999.TRMEIIMG
    FOR EACH ROW
DECLARE
    W_REC       TRMEIIMG_HIST%ROWTYPE;
    W_INS_FLG   NUMBER(1,0); 
    W_SEQ       NUMBER(10,0);
BEGIN

    -- シーケンス番号算出
    SELECT MAX(ROWNUM) + 1 INTO W_SEQ
    FROM DBCTR9999.TRMEIIMG_HIST
    WHERE GYM_ID = :NEW.GYM_ID
      AND OPERATION_DATE = :NEW.OPERATION_DATE
      AND SCAN_TERM = :NEW.SCAN_TERM
      AND BAT_ID = :NEW.BAT_ID
      AND DETAILS_NO = :NEW.DETAILS_NO
      AND IMG_KBN = :NEW.IMG_KBN
    ;

    IF ( W_SEQ IS NULL ) THEN
        W_SEQ := 1;
    END IF;

    IF ( INSERTING ) THEN
        W_INS_FLG := 1;
    END IF;
    IF ( UPDATING ) THEN
        W_INS_FLG := 2;
    END IF;

    W_REC.GYM_ID :=:NEW.GYM_ID;
    W_REC.OPERATION_DATE :=:NEW.OPERATION_DATE;
    W_REC.SCAN_TERM :=:NEW.SCAN_TERM;
    W_REC.BAT_ID :=:NEW.BAT_ID;
    W_REC.DETAILS_NO :=:NEW.DETAILS_NO;
    W_REC.IMG_KBN :=:NEW.IMG_KBN;
    W_REC.IMG_FLNM :=:NEW.IMG_FLNM;
    W_REC.IMG_FLNM_OLD :=:NEW.IMG_FLNM_OLD;
    W_REC.OC_OC_BK_NO :=:NEW.OC_OC_BK_NO;
    W_REC.OC_OC_BR_NO :=:NEW.OC_OC_BR_NO;
    W_REC.OC_IC_BK_NO :=:NEW.OC_IC_BK_NO;
    W_REC.OC_OC_DATE :=:NEW.OC_OC_DATE;
    W_REC.OC_CLEARING_DATE :=:NEW.OC_CLEARING_DATE;
    W_REC.OC_AMOUNT :=:NEW.OC_AMOUNT;
    W_REC.PAY_KBN :=:NEW.PAY_KBN;
    W_REC.UNIQUE_CODE :=:NEW.UNIQUE_CODE;
    W_REC.FILE_EXTENSION :=:NEW.FILE_EXTENSION;
    W_REC.BUA_STS :=:NEW.BUA_STS;
    W_REC.BUB_CONFIRMDATE :=:NEW.BUB_CONFIRMDATE;
    W_REC.BUA_DATE :=:NEW.BUA_DATE;
    W_REC.BUA_TIME :=:NEW.BUA_TIME;
    W_REC.GDA_DATE :=:NEW.GDA_DATE;
    W_REC.GDA_TIME :=:NEW.GDA_TIME;
    W_REC.IMG_ARCH_NAME :=:NEW.IMG_ARCH_NAME;
    W_REC.DELETE_DATE :=:NEW.DELETE_DATE;
    W_REC.DELETE_FLG :=:NEW.DELETE_FLG;
    W_REC.UPDATE_DATE := TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'));
    W_REC.UPDATE_TIME := TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'HH24MISSff3'));
    W_REC.UPDATE_KBN := W_INS_FLG;
    W_REC.SEQ := W_SEQ;

    INSERT INTO DBCTR9999.TRMEIIMG_HIST VALUES W_REC;

END;
/
ALTER TRIGGER "DBCTR9999"."TRMEIIMG_LOG_TRG" ENABLE;
exit;
