DROP TABLE dbctr9999.TRBATCHIMG;
CREATE TABLE dbctr9999.TRBATCHIMG (
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    SCAN_TERM varchar2(20) NOT NULL,
    BAT_ID number(6,0) NOT NULL,
    IMG_KBN number(2,0) NOT NULL,
    IMG_FLNM varchar2(62),
    SCAN_BATCH_FOLDER_NAME varchar2(20),
    IMG_FLNM_OLD varchar2(100),
 CONSTRAINT PK_DBCTR9999_TRBATCHIMG PRIMARY KEY (
     GYM_ID
    ,OPERATION_DATE
    ,SCAN_TERM
    ,BAT_ID
    ,IMG_KBN
));


COMMENT ON TABLE dbctr9999.TRBATCHIMG IS 'バッチイメージトランザクション';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.SCAN_TERM IS 'イメージ取込端末';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.BAT_ID IS 'バッチ番号';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.IMG_KBN IS '表裏等の別';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.IMG_FLNM IS 'バッチイメージファイル名';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.SCAN_BATCH_FOLDER_NAME IS 'スキャン連携時バッチフォルダ名';
COMMENT ON COLUMN dbctr9999.TRBATCHIMG.IMG_FLNM_OLD IS 'スキャン連携時バッチイメージファイル名';
exit;