DROP TABLE dbctr9999.DSP_PARAM;
CREATE TABLE dbctr9999.DSP_PARAM (
    GYM_ID NUMBER(3,0) NOT NULL,
    DSP_ID NUMBER(3,0) NOT NULL,
    DSP_NAME VARCHAR2(60),
    FONT_SIZE NUMBER(2,0) default 0  NOT NULL,
    DSP_WIDTH NUMBER(5,0) default 0  NOT NULL,
    DSP_HEIGHT NUMBER(5,0) default 0  NOT NULL,
    OCR_NAME VARCHAR2(40),
CONSTRAINT PK_DBCTR9999_DSP_PARAM PRIMARY KEY (
     GYM_ID
    ,DSP_ID
));
COMMENT ON TABLE dbctr9999.DSP_PARAM IS '画面パラメータ';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.DSP_NAME IS '画面名';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.FONT_SIZE IS 'フォントサイズ';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.DSP_WIDTH IS '画面サイズ(幅)';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.DSP_HEIGHT IS '画面サイズ(高さ)';
COMMENT ON COLUMN dbctr9999.DSP_PARAM.OCR_NAME IS 'ＯＣＲ帳票名 ';
exit;