DROP TABLE dbctr.GENERALTEXTMF;
CREATE TABLE dbctr.GENERALTEXTMF (
    TEXTKBN number(5,0) NOT NULL,
    RECORDKBN number(1,0) NOT NULL,
    NO number(4,0) NOT NULL,
    NAME varchar2(50),
    VALUE varchar2(160) NOT NULL,
    DESCRIPTION varchar2(200),
    ABBREVIATE varchar2(40),
CONSTRAINT PK_DBCTR_GENERALTEXTMF PRIMARY KEY (
     TEXTKBN
    ,RECORDKBN
    ,NO
    ,VALUE
));

COMMENT ON TABLE dbctr.GENERALTEXTMF IS 'テキスト汎用マスタ';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.TEXTKBN IS 'テキスト区分';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.RECORDKBN IS 'レコード区分';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.NO IS 'カラム番号';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.NAME IS 'カラム名';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.VALUE IS '値';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.DESCRIPTION IS '説明';
COMMENT ON COLUMN dbctr.GENERALTEXTMF.ABBREVIATE IS '説明略称';
exit;