--------------------------------------------------------
--  DDL for Trigger TRITEM_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DBCTR9999"."TRITEM_LOG_TRG" AFTER
    INSERT OR UPDATE ON DBCTR9999.TRITEM
    FOR EACH ROW
DECLARE
    W_REC       TRITEM_HIST%ROWTYPE;
    W_INS_FLG   NUMBER(1,0); 
    W_SEQ       NUMBER(10,0);
BEGIN
    -- シーケンス番号算出
    SELECT MAX(ROWNUM) + 1 INTO W_SEQ
    FROM DBCTR9999.TRITEM_HIST
    WHERE GYM_ID = :NEW.GYM_ID
      AND OPERATION_DATE = :NEW.OPERATION_DATE
      AND SCAN_TERM = :NEW.SCAN_TERM
      AND BAT_ID = :NEW.BAT_ID
      AND DETAILS_NO = :NEW.DETAILS_NO
      AND ITEM_ID = :NEW.ITEM_ID
    ;

    IF ( W_SEQ IS NULL ) THEN
        W_SEQ := 1;
    END IF;

    IF ( INSERTING ) THEN
        W_INS_FLG := 1;
    END IF;
    IF ( UPDATING ) THEN
        W_INS_FLG := 2;
    END IF;

    W_REC.GYM_ID :=:NEW.GYM_ID;
    W_REC.OPERATION_DATE :=:NEW.OPERATION_DATE;
    W_REC.SCAN_TERM :=:NEW.SCAN_TERM;
    W_REC.BAT_ID :=:NEW.BAT_ID;
    W_REC.DETAILS_NO :=:NEW.DETAILS_NO;
    W_REC.ITEM_ID :=:NEW.ITEM_ID;
    W_REC.ITEM_NAME :=:NEW.ITEM_NAME;
    W_REC.OCR_ENT_DATA :=:NEW.OCR_ENT_DATA;
    W_REC.OCR_VFY_DATA :=:NEW.OCR_VFY_DATA;
    W_REC.ENT_DATA :=:NEW.ENT_DATA;
    W_REC.VFY_DATA :=:NEW.VFY_DATA;
    W_REC.END_DATA :=:NEW.END_DATA;
    W_REC.BUA_DATA :=:NEW.BUA_DATA;
    W_REC.CTR_DATA :=:NEW.CTR_DATA;
    W_REC.ICTEISEI_DATA :=:NEW.ICTEISEI_DATA;
    W_REC.MRC_CHG_BEFDATA :=:NEW.MRC_CHG_BEFDATA;
    W_REC.E_TERM :=:NEW.E_TERM;
    W_REC.E_OPENO :=:NEW.E_OPENO;
    W_REC.E_STIME :=:NEW.E_STIME;
    W_REC.E_ETIME :=:NEW.E_ETIME;
    W_REC.E_YMD :=:NEW.E_YMD;
    W_REC.E_TIME :=:NEW.E_TIME;
    W_REC.V_TERM :=:NEW.V_TERM;
    W_REC.V_OPENO :=:NEW.V_OPENO;
    W_REC.V_STIME :=:NEW.V_STIME;
    W_REC.V_ETIME :=:NEW.V_ETIME;
    W_REC.V_YMD :=:NEW.V_YMD;
    W_REC.V_TIME :=:NEW.V_TIME;
    W_REC.C_TERM :=:NEW.C_TERM;
    W_REC.C_OPENO :=:NEW.C_OPENO;
    W_REC.C_STIME :=:NEW.C_STIME;
    W_REC.C_ETIME :=:NEW.C_ETIME;
    W_REC.C_YMD :=:NEW.C_YMD;
    W_REC.C_TIME :=:NEW.C_TIME;
    W_REC.O_TERM :=:NEW.O_TERM;
    W_REC.O_OPENO :=:NEW.O_OPENO;
    W_REC.O_STIME :=:NEW.O_STIME;
    W_REC.O_ETIME :=:NEW.O_ETIME;
    W_REC.O_YMD :=:NEW.O_YMD;
    W_REC.O_TIME :=:NEW.O_TIME;
    W_REC.ITEM_TOP :=:NEW.ITEM_TOP;
    W_REC.ITEM_LEFT :=:NEW.ITEM_LEFT;
    W_REC.ITEM_WIDTH :=:NEW.ITEM_WIDTH;
    W_REC.ITEM_HEIGHT :=:NEW.ITEM_HEIGHT;
    W_REC.FIX_TRIGGER :=:NEW.FIX_TRIGGER;
    W_REC.UPDATE_DATE := TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'));
    W_REC.UPDATE_TIME := TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'HH24MISSff3'));
    W_REC.UPDATE_KBN := W_INS_FLG;
    W_REC.SEQ := W_SEQ;

    INSERT INTO DBCTR9999.TRITEM_HIST VALUES W_REC;

END;
/
ALTER TRIGGER "DBCTR9999"."TRITEM_LOG_TRG" ENABLE;
exit;
