DROP TABLE dbctr9999.BALANCETXT_CTL;
CREATE TABLE dbctr9999.BALANCETXT_CTL (
    FILE_NAME varchar2(32) NOT NULL,
    FILE_ID varchar2(5),
    FILE_DIVID varchar2(3),
    BK_NO varchar2(4),
    MAKE_DATE number(8,0) default 0  NOT NULL,
    SEND_SEQ varchar2(8),
    CLEARING_DATE number(8,0) default 0  NOT NULL,
    RECORD_COUNT number(8,0) default 0  NOT NULL,
    RECV_DATE number(8,0) default 0  NOT NULL,
    RECV_TIME number(9,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR9999_BALANCETXT_CTL PRIMARY KEY (
     FILE_NAME
));

COMMENT ON TABLE dbctr9999.BALANCETXT_CTL IS '交換尻管理';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.FILE_ID IS 'ファイルID';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.FILE_DIVID IS 'ファイル識別区分';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.BK_NO IS '銀行コード';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.MAKE_DATE IS '作成日';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.SEND_SEQ IS '送信一連番号';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.CLEARING_DATE IS '交換日';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.RECORD_COUNT IS 'レコード件数';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.RECV_DATE IS '取込日';
COMMENT ON COLUMN dbctr9999.BALANCETXT_CTL.RECV_TIME IS '取込時刻';
exit;