DROP TABLE dbctr9999.RESULTTXT;
CREATE TABLE dbctr9999.RESULTTXT (
    FILE_NAME varchar2(32) NOT NULL,
    SEQ number(6,0) NOT NULL,
    RECEPTION varchar2(150),
    RET_CODE varchar2(10),
    IMG_NAME varchar2(62),
    FRONT_IMG_NAME varchar2(62),
    IMG_KBN number(2,0) default 0 ,
    FILE_OC_BK_NO varchar2(4),
    CHG_OC_BK_NO varchar2(4),
    OC_BR_NO varchar2(4),
    OC_DATE number(8,0) default 0 ,
    OC_METHOD varchar2(1),
    OC_USERID varchar2(14),
    PAY_KBN varchar2(1),
    BALANCE_FLG varchar2(1),
    MICR_IC_BK_NO varchar2(4),
    OCR_IC_BK_NO varchar2(4),
    QR_IC_BK_NO varchar2(4),
    FILE_IC_BK_NO varchar2(4),
    CHG_IC_BK_NO varchar2(4),
    TEISEI_IC_BK_NO varchar2(4),
    PAY_IC_BK_NO varchar2(4),
    PAYAFT_REV_IC_BK_NO varchar2(4),
    OCR_IC_BK_NO_CONF varchar2(3),
    OCR_AMOUNT varchar2(12),
    MICR_AMOUNT varchar2(12),
    QR_AMOUNT varchar2(12),
    FILE_AMOUNT varchar2(12),
    TEISEI_AMOUNT varchar2(12),
    PAY_AMOUNT varchar2(12),
    PAYAFT_REV_AMOUNT varchar2(12),
    OCR_AMOUNT_CONF varchar2(3),
    OC_CLEARING_DATE varchar2(8),
    TEISEI_CLEARING_DATE varchar2(8),
    CLEARING_DATE varchar2(8),
    QR_IC_BR_NO varchar2(4),
    KAMOKU varchar2(1),
    ACCOUNT varchar2(10),
    BK_CTL_NO varchar2(20),
    FREEFIELD varchar2(30),
    BILL_CODE varchar2(3),
    BILL_CODE_CONF varchar2(3),
    QR varchar2(160),
    MICR varchar2(65),
    MICR_CONF varchar2(3),
    BILL_NO varchar2(10),
    BILL_NO_CONF varchar2(3),
    FUBI_KBN_01 varchar2(1),
    ZERO_FUBINO_01 number(2,0) default 0 ,
    FUBI_KBN_02 varchar2(1),
    ZRO_FUBINO_02 number(2,0) default 0 ,
    FUBI_KBN_03 varchar2(1),
    ZRO_FUBINO_03 number(2,0) default 0 ,
    FUBI_KBN_04 varchar2(1),
    ZRO_FUBINO_04 number(2,0) default 0 ,
    FUBI_KBN_05 varchar2(1),
    ZRO_FUBINO_05 number(2,0) default 0 ,
    IC_FLG varchar2(1),
 CONSTRAINT PK_DBCTR9999_RESULTTXT PRIMARY KEY (
     FILE_NAME
    ,SEQ
));
COMMENT ON TABLE dbctr9999.RESULTTXT IS '結果テキスト';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN dbctr9999.RESULTTXT.SEQ IS '連番';
COMMENT ON COLUMN dbctr9999.RESULTTXT.RECEPTION IS '受付内容';
COMMENT ON COLUMN dbctr9999.RESULTTXT.RET_CODE IS '処理結果コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.IMG_NAME IS '証券イメージファイル名';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FRONT_IMG_NAME IS '表証券イメージファイル名';
COMMENT ON COLUMN dbctr9999.RESULTTXT.IMG_KBN IS '表裏等の別';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FILE_OC_BK_NO IS 'ファイル名持出銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.CHG_OC_BK_NO IS '読替持出銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OC_BR_NO IS '持出支店コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OC_DATE IS '持出日';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OC_METHOD IS '持出時接続方式';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OC_USERID IS 'ユーザID(持出者)';
COMMENT ON COLUMN dbctr9999.RESULTTXT.PAY_KBN IS '決済対象区分';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BALANCE_FLG IS '交換尻確定フラグ';
COMMENT ON COLUMN dbctr9999.RESULTTXT.MICR_IC_BK_NO IS 'MICR持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OCR_IC_BK_NO IS 'OCR持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.QR_IC_BK_NO IS 'QRコード持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FILE_IC_BK_NO IS 'ファイル名持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.CHG_IC_BK_NO IS '読替持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.TEISEI_IC_BK_NO IS '証券データ訂正持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.PAY_IC_BK_NO IS '決済持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.PAYAFT_REV_IC_BK_NO IS '決済後訂正持帰銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OCR_IC_BK_NO_CONF IS 'OCR持帰銀行コード確信度';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OCR_AMOUNT IS 'OCR金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.MICR_AMOUNT IS 'MICR金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.QR_AMOUNT IS 'QRコード金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FILE_AMOUNT IS 'ファイル名金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.TEISEI_AMOUNT IS '証券データ訂正金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.PAY_AMOUNT IS '決済金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.PAYAFT_REV_AMOUNT IS '決済後訂正金額';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OCR_AMOUNT_CONF IS 'OCR金額確信度';
COMMENT ON COLUMN dbctr9999.RESULTTXT.OC_CLEARING_DATE IS '持出時交換希望日';
COMMENT ON COLUMN dbctr9999.RESULTTXT.TEISEI_CLEARING_DATE IS '証券データ訂正交換希望日';
COMMENT ON COLUMN dbctr9999.RESULTTXT.CLEARING_DATE IS '交換日';
COMMENT ON COLUMN dbctr9999.RESULTTXT.QR_IC_BR_NO IS 'QRコード持帰支店コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.KAMOKU IS '科目コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ACCOUNT IS '口座番号';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BK_CTL_NO IS '銀行管理番号';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FREEFIELD IS '自由記述欄';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BILL_CODE IS '交換証券種類コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BILL_CODE_CONF IS '交換証券種類コード確信度';
COMMENT ON COLUMN dbctr9999.RESULTTXT.QR IS 'QRコード情報';
COMMENT ON COLUMN dbctr9999.RESULTTXT.MICR IS 'MICR情報';
COMMENT ON COLUMN dbctr9999.RESULTTXT.MICR_CONF IS 'MICR情報確信度';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BILL_NO IS '手形・小切手番号';
COMMENT ON COLUMN dbctr9999.RESULTTXT.BILL_NO_CONF IS '手形・小切手番号確信度';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FUBI_KBN_01 IS '不渡返還区分１';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ZERO_FUBINO_01 IS '0号不渡事由コード１';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FUBI_KBN_02 IS '不渡返還区分２';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ZRO_FUBINO_02 IS '0号不渡事由コード２';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FUBI_KBN_03 IS '不渡返還区分３';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ZRO_FUBINO_03 IS '0号不渡事由コード３';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FUBI_KBN_04 IS '不渡返還区分４';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ZRO_FUBINO_04 IS '0号不渡事由コード４';
COMMENT ON COLUMN dbctr9999.RESULTTXT.FUBI_KBN_05 IS '不渡返還区分５';
COMMENT ON COLUMN dbctr9999.RESULTTXT.ZRO_FUBINO_05 IS '0号不渡事由コード５';
COMMENT ON COLUMN dbctr9999.RESULTTXT.IC_FLG IS '持帰状況フラグ';
exit;