DROP TABLE dbctr9999.CTR_OCR_PARAM;
CREATE TABLE dbctr9999.CTR_OCR_PARAM (
    ITEM_NAME varchar2(30) NOT NULL,
    ITEM_TYPE varchar2(30) NOT NULL,
    CTR_PRIORITY number(2,0) default 0  NOT NULL,
    PKG_PRIORITY number(2,0) default 0  NOT NULL,
    LOWER_LIMIT number(3,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR9999_CTR_OCR_PARAM PRIMARY KEY (
     ITEM_NAME
    ,ITEM_TYPE
));
COMMENT ON TABLE dbctr9999.CTR_OCR_PARAM IS '電子交換所OCRパラメータ';
COMMENT ON COLUMN dbctr9999.CTR_OCR_PARAM.ITEM_NAME IS '認識項目';
COMMENT ON COLUMN dbctr9999.CTR_OCR_PARAM.ITEM_TYPE IS '認識タイプ';
COMMENT ON COLUMN dbctr9999.CTR_OCR_PARAM.CTR_PRIORITY IS '電子交換所優先度:電子交換所優先度を設定';
COMMENT ON COLUMN dbctr9999.CTR_OCR_PARAM.PKG_PRIORITY IS 'パッケージ優先度:パッケージ内の優先度を設定';
COMMENT ON COLUMN dbctr9999.CTR_OCR_PARAM.LOWER_LIMIT IS '下限値:確信度和算値の下限値を設定 下限値を下回る場合は、不読とする';
exit;