DROP TABLE dbctr9999.ITEM_MASTER;
CREATE TABLE dbctr9999.ITEM_MASTER (
    ITEM_ID number(3,0) NOT NULL,
    ITEM_NAME varchar2(40),
CONSTRAINT PK_DBCTR9999_ITEM_MASTER PRIMARY KEY (
     ITEM_ID
));
COMMENT ON TABLE dbctr9999.ITEM_MASTER IS 'çÄñ⁄íËã`';
COMMENT ON COLUMN dbctr9999.ITEM_MASTER.ITEM_ID IS 'çÄñ⁄î‘çÜ';
COMMENT ON COLUMN dbctr9999.ITEM_MASTER.ITEM_NAME IS 'çÄñ⁄ñºèÃ';
exit;