--------------------------------------------------------
--  DDL for Trigger TRMEI_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DBCTR9999"."TRMEI_LOG_TRG" AFTER
    INSERT OR UPDATE ON DBCTR9999.TRMEI
    FOR EACH ROW
DECLARE
    W_REC       TRMEI_HIST%ROWTYPE;
    W_INS_FLG   NUMBER(1,0); 
    W_SEQ       NUMBER(10,0);
BEGIN

    -- シーケンス番号算出
    SELECT MAX(ROWNUM) + 1 INTO W_SEQ
    FROM DBCTR9999.TRMEI_HIST
    WHERE GYM_ID = :NEW.GYM_ID
      AND OPERATION_DATE = :NEW.OPERATION_DATE
      AND SCAN_TERM = :NEW.SCAN_TERM
      AND BAT_ID = :NEW.BAT_ID
      AND DETAILS_NO = :NEW.DETAILS_NO
    ;

    IF ( W_SEQ IS NULL ) THEN
        W_SEQ := 1;
    END IF;

    IF ( INSERTING ) THEN
        W_INS_FLG := 1;
    END IF;
    IF ( UPDATING ) THEN
        W_INS_FLG := 2;
    END IF;

    W_REC.GYM_ID :=:NEW.GYM_ID;
    W_REC.OPERATION_DATE :=:NEW.OPERATION_DATE;
    W_REC.SCAN_TERM :=:NEW.SCAN_TERM;
    W_REC.BAT_ID :=:NEW.BAT_ID;
    W_REC.DETAILS_NO :=:NEW.DETAILS_NO;
    W_REC.DSP_ID :=:NEW.DSP_ID;
    W_REC.IC_OC_BK_NO :=:NEW.IC_OC_BK_NO;
    W_REC.IC_OLD_OC_BK_NO :=:NEW.IC_OLD_OC_BK_NO;
    W_REC.BUA_DATE :=:NEW.BUA_DATE;
    W_REC.BUB_DATE :=:NEW.BUB_DATE;
    W_REC.BCA_DATE :=:NEW.BCA_DATE;
    W_REC.GMA_DATE :=:NEW.GMA_DATE;
    W_REC.GMB_DATE :=:NEW.GMB_DATE;
    W_REC.GRA_DATE :=:NEW.GRA_DATE;
    W_REC.GXA_DATE :=:NEW.GXA_DATE;
    W_REC.GXB_DATE :=:NEW.GXB_DATE;
    W_REC.MRA_DATE :=:NEW.MRA_DATE;
    W_REC.MRB_DATE :=:NEW.MRB_DATE;
    W_REC.MRC_DATE :=:NEW.MRC_DATE;
    W_REC.MRD_DATE :=:NEW.MRD_DATE;
    W_REC.YCA_MARK :=:NEW.YCA_MARK;
    W_REC.EDIT_FLG :=:NEW.EDIT_FLG;
    W_REC.BCA_STS :=:NEW.BCA_STS;
    W_REC.GMA_STS :=:NEW.GMA_STS;
    W_REC.GRA_STS :=:NEW.GRA_STS;
    W_REC.GRA_CONFIRMDATE :=:NEW.GRA_CONFIRMDATE;
    W_REC.DELETE_DATE :=:NEW.DELETE_DATE;
    W_REC.DELETE_FLG :=:NEW.DELETE_FLG;
    W_REC.UPDATE_DATE := TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'));
    W_REC.UPDATE_TIME := TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'HH24MISSff3'));
    W_REC.UPDATE_KBN := W_INS_FLG;
    W_REC.SEQ := W_SEQ;

    INSERT INTO DBCTR9999.TRMEI_HIST VALUES W_REC;

END;
/
ALTER TRIGGER "DBCTR9999"."TRMEI_LOG_TRG" ENABLE;
exit;
