DROP TABLE dbctr9999.BALANCETXT;
CREATE TABLE dbctr9999.BALANCETXT (
    FILE_NAME varchar2(32) NOT NULL,
    BK_NO varchar2(4) NOT NULL,
    CONFIRM_FLG varchar2(1),
    LOAN_KBN number(1,0),
    PAY_AMOUNT varchar2(16),
CONSTRAINT PK_DBCTR9999_BALANCETXT PRIMARY KEY (
     FILE_NAME
    ,BK_NO
));

COMMENT ON TABLE dbctr9999.BALANCETXT IS '交換尻';
COMMENT ON COLUMN dbctr9999.BALANCETXT.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN dbctr9999.BALANCETXT.BK_NO IS '銀行コード';
COMMENT ON COLUMN dbctr9999.BALANCETXT.CONFIRM_FLG IS '確定フラグ';
COMMENT ON COLUMN dbctr9999.BALANCETXT.LOAN_KBN IS '借貸区分コード';
COMMENT ON COLUMN dbctr9999.BALANCETXT.PAY_AMOUNT IS '決済金額';
exit;