DROP TABLE dbctr9999.TSUCHITXT;
CREATE TABLE dbctr9999.TSUCHITXT (
    FILE_NAME varchar2(32) NOT NULL,
    RECORD_SEQ number(8,0) NOT NULL,
    IMG_NAME varchar2(62),
    BK_NO_TEISEI_FLG varchar2(1),
    TEISEI_BEF_BK_NO varchar2(4),
    TEISEI_AFT_BK_NO varchar2(4),
    CLEARING_TEISEI_FLG varchar2(1),
    TEISEI_BEF_CLEARING_DATE varchar2(8),
    TEISEI_CLEARING_DATE varchar2(8),
    AMOUNT_TEISEI_FLG varchar2(1),
    TEISEI_BEF_AMOUNT varchar2(12),
    TEISEI_AMOUNT varchar2(12),
    DUPLICATE_IMG_NAME varchar2(62),
    FUBI_REG_KBN varchar2(1),
    FUBI_KBN_01 varchar2(1),
    ZERO_FUBINO_01 number(2,0) default 0  NOT NULL,
    FUBI_KBN_02 varchar2(1),
    ZRO_FUBINO_02 number(2,0) default 0  NOT NULL,
    FUBI_KBN_03 varchar2(1),
    ZRO_FUBINO_03 number(2,0) default 0  NOT NULL,
    FUBI_KBN_04 varchar2(1),
    ZRO_FUBINO_04 number(2,0) default 0  NOT NULL,
    FUBI_KBN_05 varchar2(1),
    ZRO_FUBINO_05 number(2,0) default 0  NOT NULL,
    REV_CLEARING_FLG varchar2(1),
 CONSTRAINT PK_DBCTR9999_TSUCHITXT PRIMARY KEY (
     FILE_NAME
    ,RECORD_SEQ
));
COMMENT ON TABLE dbctr9999.TSUCHITXT IS '通知テキスト';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.RECORD_SEQ IS 'レコード連番';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.IMG_NAME IS '証券イメージファイル名';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.BK_NO_TEISEI_FLG IS '銀行コード訂正フラグ';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_BEF_BK_NO IS '訂正前銀行コード';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_AFT_BK_NO IS '訂正後銀行コード';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.CLEARING_TEISEI_FLG IS '交換希望日訂正フラグ';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_BEF_CLEARING_DATE IS '訂正前交換希望日';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_CLEARING_DATE IS '訂正後交換希望日';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.AMOUNT_TEISEI_FLG IS '金額訂正フラグ';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_BEF_AMOUNT IS '訂正前金額';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.TEISEI_AMOUNT IS '訂正後金額';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.DUPLICATE_IMG_NAME IS '二重持出イメージファイル名';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_REG_KBN IS '不渡返還登録区分';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_KBN_01 IS '不渡返還区分１';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.ZERO_FUBINO_01 IS '0号不渡事由コード１';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_KBN_02 IS '不渡返還区分２';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.ZRO_FUBINO_02 IS '0号不渡事由コード２';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_KBN_03 IS '不渡返還区分３';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.ZRO_FUBINO_03 IS '0号不渡事由コード３';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_KBN_04 IS '不渡返還区分４';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.ZRO_FUBINO_04 IS '0号不渡事由コード４';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.FUBI_KBN_05 IS '不渡返還区分５';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.ZRO_FUBINO_05 IS '0号不渡事由コード５';
COMMENT ON COLUMN dbctr9999.TSUCHITXT.REV_CLEARING_FLG IS '逆交換対象フラグ:逆交換対象フラグをセットする。';
exit;