DROP TABLE dbctr9999.CTR_MICRCUTINFO_PARAM;
CREATE TABLE dbctr9999.CTR_MICRCUTINFO_PARAM (
    ITEM_NAME varchar2(30) NOT NULL,
    SEQ number(6,0) NOT NULL,
    REGEXPATTERN varchar2(50),
 CONSTRAINT PK_DBCTR9999_CTR_MICRCUTINFO_PARAM PRIMARY KEY (
     ITEM_NAME
    ,SEQ
));
COMMENT ON TABLE dbctr9999.CTR_MICRCUTINFO_PARAM IS '電子交換所MICR切出情報パラメータ';
COMMENT ON COLUMN dbctr9999.CTR_MICRCUTINFO_PARAM.ITEM_NAME IS '認識項目';
COMMENT ON COLUMN dbctr9999.CTR_MICRCUTINFO_PARAM.SEQ IS '連番';
COMMENT ON COLUMN dbctr9999.CTR_MICRCUTINFO_PARAM.REGEXPATTERN IS '正規表現パターン';
exit;