DROP TABLE dbctr.CHANGE_DSPIDMF;
CREATE TABLE dbctr.CHANGE_DSPIDMF (
    BILL_CODE number(3,0) NOT NULL,
    DSP_ID number(3,0) default 999  NOT NULL,
CONSTRAINT PK_DBCTR_CHANGE_DSPIDMF PRIMARY KEY (
     BILL_CODE
));

COMMENT ON TABLE dbctr.CHANGE_DSPIDMF IS '画面番号変換マスタ';
COMMENT ON COLUMN dbctr.CHANGE_DSPIDMF.BILL_CODE IS '証券種類コード';
COMMENT ON COLUMN dbctr.CHANGE_DSPIDMF.DSP_ID IS '画面番号';
exit;