DROP TABLE dbctr9999.FILE_PARAM;
CREATE TABLE dbctr9999.FILE_PARAM (
    FILE_ID varchar2(5) NOT NULL,
    FILE_DIVID varchar2(3) NOT NULL,
    FILE_NAME varchar2(100),
    FILE_COURSE number(1,0) default -1 ,
    FILE_TYPE number(1,0) default -1 ,
    FILE_LENGTH number(4,0) default 0 ,
    FILE_EXTENSION varchar2(4),
    RET_FILE_ID varchar2(5),
    RET_FILE_DIVID varchar2(3),
CONSTRAINT PK_DBCTR9999_FILE_PARAM PRIMARY KEY (
     FILE_ID
    ,FILE_DIVID
));
COMMENT ON TABLE dbctr9999.FILE_PARAM IS 'ファイルパラメータ';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_ID IS 'ファイルID';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_DIVID IS 'ファイル識別区分';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_NAME IS 'ファイル名称';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_COURSE IS '送受信経路:0：送信 1：受信';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_TYPE IS '経路区分:0：リターン型 1：プッシュ型';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_LENGTH IS 'レコード長:バイト';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.FILE_EXTENSION IS '拡張子:”.”含む';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.RET_FILE_ID IS 'リターンファイルID';
COMMENT ON COLUMN dbctr9999.FILE_PARAM.RET_FILE_DIVID IS 'リターンファイル識別区分';
exit;