DROP TABLE dbctr9999.PAYERMF;
CREATE TABLE dbctr9999.PAYERMF (
    BR_NO number(4,0) NOT NULL,
    ACCOUNT_NO number(8,0) NOT NULL,
    NAME_KANJI varchar2(30),
    NAME_KANA varchar2(30),
CONSTRAINT PK_DBCTR9999_PAYERMF PRIMARY KEY (
     BR_NO
    ,ACCOUNT_NO
));
COMMENT ON TABLE dbctr9999.PAYERMF IS '支払人マスタ';
COMMENT ON COLUMN dbctr9999.PAYERMF.BR_NO IS '支店番号';
COMMENT ON COLUMN dbctr9999.PAYERMF.ACCOUNT_NO IS '口座番号';
COMMENT ON COLUMN dbctr9999.PAYERMF.NAME_KANJI IS '支払人名漢字';
COMMENT ON COLUMN dbctr9999.PAYERMF.NAME_KANA IS '支払人名カナ';
exit;