DROP TABLE dbctr9999.BRANCHMF;
CREATE TABLE dbctr9999.BRANCHMF (
    BR_NO number(4,0) NOT NULL,
    BR_NAME_KANJI varchar2(30) NOT NULL,
    BR_NAME_KANA varchar2(30),
CONSTRAINT PK_DBCTR9999_BRANCHMF PRIMARY KEY (
     BR_NO
));
COMMENT ON TABLE dbctr9999.BRANCHMF IS 'éxìXÉ}ÉXÉ^';
COMMENT ON COLUMN dbctr9999.BRANCHMF.BR_NO IS 'éxìXî‘çÜ';
COMMENT ON COLUMN dbctr9999.BRANCHMF.BR_NAME_KANJI IS 'äøéöñºèÃ';
COMMENT ON COLUMN dbctr9999.BRANCHMF.BR_NAME_KANA IS 'ÉJÉiñºèÃ';
exit;