DROP TABLE dbctr9999.SEND_FILE_TRMEI PURGE;
CREATE TABLE dbctr9999.SEND_FILE_TRMEI (
    SEND_FILE_NAME varchar2(32) NOT NULL,
    GYM_ID number(3,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    SCAN_TERM varchar2(20) NOT NULL,
    BAT_ID number(6,0) NOT NULL,
    DETAILS_NO number(6,0) NOT NULL,
CONSTRAINT PK_DBCTR9999_SEND_FILE_TRMEI PRIMARY KEY (
     SEND_FILE_NAME,GYM_ID,OPERATION_DATE,SCAN_TERM,BAT_ID,DETAILS_NO
));
COMMENT ON TABLE dbctr9999.SEND_FILE_TRMEI IS '配信ファイル明細内訳';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.SEND_FILE_NAME IS '配信ファイル名';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.GYM_ID IS 'TRMEIキー情報';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.OPERATION_DATE IS 'TRMEIキー情報';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.SCAN_TERM IS 'TRMEIキー情報';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.BAT_ID IS 'TRMEIキー情報';
COMMENT ON COLUMN dbctr9999.SEND_FILE_TRMEI.DETAILS_NO IS 'TRMEIキー情報';
exit;