DROP TABLE dbctr9999.BILLMEITXT_CTL;
CREATE TABLE dbctr9999.BILLMEITXT_CTL (
    TXTNAME varchar2(32) NOT NULL,
    FILE_ID varchar2(5),
    FILE_DIVID varchar2(3),
    BK_NO varchar2(4),
    CREATE_DATE number(8,0),
    SEND_SEQ varchar2(8),
    PAY_RECORD_COUNT number(8,0),
    PAY_TOTAL_AMOUNT number(16,0),
    PAY_TOTAL_COUNT number(8,0),
    NONEPAY_RECORD_COUNT number(8,0),
    NONEPAY_TOTAL_AMOUNT number(16,0),
    NONEPAY_TOTAL_COUNT number(8,0),
    OTHER_FRONT_COUNT number(8,0),
CONSTRAINT PK_DBCTR9999_BILLMEITXT_CTL PRIMARY KEY (
     TXTNAME
));
COMMENT ON TABLE dbctr9999.BILLMEITXT_CTL IS '証券明細テキスト管理';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.TXTNAME IS '証券明細テキスト名';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.FILE_ID IS 'ファイルID';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.FILE_DIVID IS 'ファイル識別区分';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.BK_NO IS '銀行コード';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.CREATE_DATE IS '作成日';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.SEND_SEQ IS '送信一連番号';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.PAY_RECORD_COUNT IS '決済対象レコード件数';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.PAY_TOTAL_AMOUNT IS '決済対象合計金額';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.PAY_TOTAL_COUNT IS '決済対象合計枚数';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.NONEPAY_RECORD_COUNT IS '決済対象外レコード件数';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.NONEPAY_TOTAL_AMOUNT IS '決済対象外合計金額';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.NONEPAY_TOTAL_COUNT IS '決済対象外合計枚数';
COMMENT ON COLUMN dbctr9999.BILLMEITXT_CTL.OTHER_FRONT_COUNT IS '表以外レコード件数';
exit;