DROP TABLE dbctr.IC_OCR_FINISH;
CREATE TABLE dbctr.IC_OCR_FINISH (
    FRONT_IMG_NAME varchar2(62) NOT NULL,
    OPERATION_DATE number(8,0) default -1  NOT NULL,
 CONSTRAINT PK_DBCTR_IC_OCR_FINISH PRIMARY KEY (
     FRONT_IMG_NAME
));

COMMENT ON TABLE dbctr.IC_OCR_FINISH IS '持帰OCR完了明細';
COMMENT ON COLUMN dbctr.IC_OCR_FINISH.FRONT_IMG_NAME IS '表イメージファイル名';
COMMENT ON COLUMN dbctr.IC_OCR_FINISH.OPERATION_DATE IS '処理日';
exit;

