DROP TABLE dbctr9999.LOCK_BANK_PROCESS;
CREATE TABLE dbctr9999.LOCK_BANK_PROCESS (
    GYM_ID number(3,0) NOT NULL,
    APP_ID varchar2(20) NOT NULL,
    CREATE_DATE number(8,0) NOT NULL,
    CREATE_TIME number(9,0) NOT NULL,
CONSTRAINT PK_DBCTR9999_LOCK_BANK_PROCESS PRIMARY KEY (
     GYM_ID
    ,APP_ID
));
COMMENT ON TABLE dbctr9999.LOCK_BANK_PROCESS IS '銀行別業務ロック';
COMMENT ON COLUMN dbctr9999.LOCK_BANK_PROCESS.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.LOCK_BANK_PROCESS.APP_ID IS 'アプリケーションID';
COMMENT ON COLUMN dbctr9999.LOCK_BANK_PROCESS.CREATE_DATE IS '作成日付';
COMMENT ON COLUMN dbctr9999.LOCK_BANK_PROCESS.CREATE_TIME IS '作成時刻';
exit;