DROP TABLE dbctr9999.IMG_PARAM;
CREATE TABLE dbctr9999.IMG_PARAM (
    GYM_ID NUMBER(3,0) NOT NULL,
    DSP_ID NUMBER(3,0) NOT NULL,
    IMG_FILE VARCHAR2(30),
    REDUCE_RATE NUMBER(4,1) default 0  NOT NULL,
    IMG_TOP NUMBER(10,1) default -1  NOT NULL,
    IMG_LEFT NUMBER(10,1) default -1  NOT NULL,
    IMG_WIDTH NUMBER(10,1) default -1  NOT NULL,
    IMG_HEIGHT NUMBER(10,1) default -1  NOT NULL,
    IMG_BASE_POINT NUMBER(10,1) default -1  NOT NULL,
    XSCROLL_LEFT NUMBER(10,1) default 0  NOT NULL,
    XSCROLL_VALUE NUMBER(4,0) default 0  NOT NULL,
    XSCROLL_RIGHT NUMBER(10,1) default 0  NOT NULL,
CONSTRAINT PK_DBCTR9999_IMG_PARAM PRIMARY KEY (
     GYM_ID
    ,DSP_ID
));
COMMENT ON TABLE dbctr9999.IMG_PARAM IS 'イメージパラメータ';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_FILE IS 'サンプルイメージファイル';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.REDUCE_RATE IS '縮小率';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_TOP IS 'TOP基点';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_LEFT IS 'LEFT基点';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_WIDTH IS '幅';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_HEIGHT IS '高さ';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.IMG_BASE_POINT IS 'イメージ内基点';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.XSCROLL_LEFT IS '水平スクロール-左基準';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.XSCROLL_VALUE IS '水平スクロール-スクロール位置';
COMMENT ON COLUMN dbctr9999.IMG_PARAM.XSCROLL_RIGHT IS '右基準位置';
exit;