--------------------------------------------------------
--  DDL for Trigger TRBATCH_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DBCTR9999"."TRBATCH_LOG_TRG" AFTER
    INSERT OR UPDATE ON DBCTR9999.TRBATCH
    FOR EACH ROW
DECLARE
    W_REC       TRBATCH_HIST%ROWTYPE;
    W_INS_FLG   NUMBER(1,0); 
    W_SEQ       NUMBER(10,0);
BEGIN

    -- シーケンス番号算出
    SELECT MAX(ROWNUM) + 1 INTO W_SEQ
    FROM DBCTR9999.TRBATCH_HIST
    WHERE GYM_ID = :NEW.GYM_ID
      AND OPERATION_DATE = :NEW.OPERATION_DATE
      AND SCAN_TERM = :NEW.SCAN_TERM
      AND BAT_ID = :NEW.BAT_ID
    ;

    IF ( W_SEQ IS NULL ) THEN
        W_SEQ := 1;
    END IF;

    IF ( INSERTING ) THEN
        W_INS_FLG := 1;
    END IF;
    IF ( UPDATING ) THEN
        W_INS_FLG := 2;
    END IF;

    W_REC.GYM_ID :=:NEW.GYM_ID;
    W_REC.OPERATION_DATE :=:NEW.OPERATION_DATE;
    W_REC.SCAN_TERM :=:NEW.SCAN_TERM;
    W_REC.BAT_ID :=:NEW.BAT_ID;
    W_REC.STS :=:NEW.STS;
    W_REC.INPUT_ROUTE :=:NEW.INPUT_ROUTE;
    W_REC.OC_BK_NO :=:NEW.OC_BK_NO;
    W_REC.OC_BR_NO :=:NEW.OC_BR_NO;
    W_REC.SCAN_BR_NO :=:NEW.SCAN_BR_NO;
    W_REC.SCAN_DATE :=:NEW.SCAN_DATE;
    W_REC.CLEARING_DATE :=:NEW.CLEARING_DATE;
    W_REC.SCAN_COUNT :=:NEW.SCAN_COUNT;
    W_REC.TOTAL_COUNT :=:NEW.TOTAL_COUNT;
    W_REC.TOTAL_AMOUNT :=:NEW.TOTAL_AMOUNT;
    W_REC.DELETE_DATE :=:NEW.DELETE_DATE;
    W_REC.DELETE_FLG :=:NEW.DELETE_FLG;
    W_REC.E_TERM :=:NEW.E_TERM;
    W_REC.E_OPENO :=:NEW.E_OPENO;
    W_REC.E_YMD :=:NEW.E_YMD;
    W_REC.E_TIME :=:NEW.E_TIME;
    W_REC.UPDATE_DATE := TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'));
    W_REC.UPDATE_TIME := TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'HH24MISSff3'));
    W_REC.UPDATE_KBN := W_INS_FLG;
    W_REC.SEQ := W_SEQ;

    INSERT INTO DBCTR9999.TRBATCH_HIST VALUES W_REC;

END;
/
ALTER TRIGGER "DBCTR9999"."TRBATCH_LOG_TRG" ENABLE;
exit;
