DROP TABLE dbctr9999.FILE_SEQ;
CREATE TABLE dbctr9999.FILE_SEQ (
    SEND_DATE number(8,0) NOT NULL,
    LAST_SEQ number(8,0) default 0  NOT NULL,
    LAST_SEQ_DATE number(8,0) default 0  NOT NULL,
    LAST_SEQ_TIME number(11,0) default 0  NOT NULL,
    LAST_FILE_ID varchar2(5),
    LAST_FILE_DIVID varchar2(3),
CONSTRAINT PK_DBCTR9999_FILE_SEQ PRIMARY KEY (
     SEND_DATE
));
COMMENT ON TABLE dbctr9999.FILE_SEQ IS 'ファイル一連番号採番';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.SEND_DATE IS '送信日';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.LAST_SEQ IS '最終一連番号:0：初期値 使用時に使用番号にカウントアップ 日初処理時に0クリア';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.LAST_SEQ_DATE IS '最終採番日付';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.LAST_SEQ_TIME IS '最終採番時刻';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.LAST_FILE_ID IS '最終採番ファイルID';
COMMENT ON COLUMN dbctr9999.FILE_SEQ.LAST_FILE_DIVID IS '最終採番ファイル識別区分';
exit;