DROP TABLE dbctr9999.RESULTTXT_CTL;
CREATE TABLE dbctr9999.RESULTTXT_CTL (
    FILE_NAME varchar2(32) NOT NULL,
    FILE_ID varchar2(5),
    FILE_DIVID varchar2(3),
    BK_NO varchar2(4),
    MAKE_DATE number(8,0) default 0  NOT NULL,
    SEND_SEQ varchar2(8),
    RECEPTION_ID varchar2(5),
    PROC_FILE_NAME varchar2(35),
    FILE_CHK_CODE varchar2(10),
    RECORD_COUNT number(8,0) default 0  NOT NULL,
    RECV_DATE number(8,0) default 0  NOT NULL,
    RECV_TIME number(9,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR9999_RESULTTXT_CTL PRIMARY KEY (
     FILE_NAME
));
COMMENT ON TABLE dbctr9999.RESULTTXT_CTL IS '結果テキスト管理';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.FILE_NAME IS 'ファイル名';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.FILE_ID IS 'ファイルID';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.FILE_DIVID IS 'ファイル識別区分';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.BK_NO IS '銀行コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.MAKE_DATE IS '作成日';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.SEND_SEQ IS '送信一連番号';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.RECEPTION_ID IS '受付ファイルID';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.PROC_FILE_NAME IS '処理対象ファイル名';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.FILE_CHK_CODE IS 'ファイルチェック結果コード';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.RECORD_COUNT IS 'レコード件数';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.RECV_DATE IS '取込日';
COMMENT ON COLUMN dbctr9999.RESULTTXT_CTL.RECV_TIME IS '取込時刻';
exit;