DROP TABLE dbctr.OCR_DATA;
CREATE TABLE dbctr.OCR_DATA (
    GYM_ID number(3,0) NOT NULL,
    INPUT_ROUTE number(1,0) NOT NULL,
    OPERATION_DATE number(8,0) NOT NULL,
    IMG_DIRNAME varchar2(100) NOT NULL,
    IMG_NAME varchar2(62) NOT NULL,
    FIELD_NAME varchar2(200) NOT NULL,
    CONFIDENCE number(2,0) default 0  NOT NULL,
    OCR varchar2(200),
    ITEM_TOP number(10,1) default -1  NOT NULL,
    ITEM_LEFT number(10,1) default -1  NOT NULL,
    ITEM_WIDTH number(10,1) default -1  NOT NULL,
    ITEM_HEIGHT number(10,1) default -1  NOT NULL,
 CONSTRAINT PK_DBCTR_OCR_DATA PRIMARY KEY (
     GYM_ID
    ,INPUT_ROUTE
    ,OPERATION_DATE
    ,IMG_DIRNAME
    ,IMG_NAME
    ,FIELD_NAME
));
COMMENT ON TABLE dbctr.OCR_DATA IS 'OCR認識結果';
COMMENT ON COLUMN dbctr.OCR_DATA.GYM_ID IS '業務番号';
COMMENT ON COLUMN dbctr.OCR_DATA.INPUT_ROUTE IS '取込ルート:1:通常バッチルート 2:付帯バッチルート 0:その他';
COMMENT ON COLUMN dbctr.OCR_DATA.OPERATION_DATE IS '処理日';
COMMENT ON COLUMN dbctr.OCR_DATA.IMG_DIRNAME IS 'イメージフォルダ名';
COMMENT ON COLUMN dbctr.OCR_DATA.IMG_NAME IS 'イメージファイル名';
COMMENT ON COLUMN dbctr.OCR_DATA.FIELD_NAME IS '読取フィールド名';
COMMENT ON COLUMN dbctr.OCR_DATA.CONFIDENCE IS '信頼度';
COMMENT ON COLUMN dbctr.OCR_DATA.OCR IS 'ＯＣＲ結果';
COMMENT ON COLUMN dbctr.OCR_DATA.ITEM_TOP IS 'OCR認識項目位置(TOP)';
COMMENT ON COLUMN dbctr.OCR_DATA.ITEM_LEFT IS 'OCR認識項目位置(LEFT)';
COMMENT ON COLUMN dbctr.OCR_DATA.ITEM_WIDTH IS 'OCR認識項目位置(WIDTH)';
COMMENT ON COLUMN dbctr.OCR_DATA.ITEM_HEIGHT IS 'OCR認識項目位置(HEIGHT)';
exit;