DROP TABLE dbctr.FUWATARIMF;
CREATE TABLE dbctr.FUWATARIMF (
    CODE number(3,0) NOT NULL,
    KBN_NAME varchar2(60) NOT NULL,
    FUBI_JIYUU varchar2(60) NOT NULL,
    DESCRIPTION varchar2(100),
CONSTRAINT PK_DBCTR_FUWATARIMF PRIMARY KEY (
     CODE
));
COMMENT ON TABLE dbctr.FUWATARIMF IS '不渡事由コードマスタ';
COMMENT ON COLUMN dbctr.FUWATARIMF.CODE IS 'コード';
COMMENT ON COLUMN dbctr.FUWATARIMF.KBN_NAME IS '区分名称';
COMMENT ON COLUMN dbctr.FUWATARIMF.FUBI_JIYUU IS '不備事由';
COMMENT ON COLUMN dbctr.FUWATARIMF.DESCRIPTION IS '備考';
exit;