DROP TABLE dbctr9999.CTRUSERINFO;
CREATE TABLE dbctr9999.CTRUSERINFO (
    USERID varchar2(14) NOT NULL,
    S_DATE number(8,0) default 0  NOT NULL,
    PASSWORD varchar2(64),
    E_DATE number(8,0) default 99991231  NOT NULL,
CONSTRAINT PK_DBCTR9999_CTRUSERINFO PRIMARY KEY (
     USERID
    ,S_DATE
));
COMMENT ON TABLE dbctr9999.CTRUSERINFO IS '電子交換ユーザー情報マスタ';
COMMENT ON COLUMN dbctr9999.CTRUSERINFO.USERID IS 'ユーザID:電子交換所登録内容';
COMMENT ON COLUMN dbctr9999.CTRUSERINFO.S_DATE IS '有効期限開始日:電子交換所登録内容';
COMMENT ON COLUMN dbctr9999.CTRUSERINFO.PASSWORD IS 'パスワード:電子交換所登録内容';
COMMENT ON COLUMN dbctr9999.CTRUSERINFO.E_DATE IS '有効期限終了日:電子交換所登録内容';
exit;