DROP TABLE dbctr9999.CHANGEMF;
CREATE TABLE dbctr9999.CHANGEMF (
    OLD_BR_NO number(4,0) NOT NULL,
    OLD_ACCOUNT_NO number(8,0) NOT NULL,
    NEW_BR_NO number(4,0) default -1  NOT NULL,
    NEW_ACCOUNT_NO number(8,0) default -1  NOT NULL,
    DESCRIPTION varchar2(100),
CONSTRAINT PK_DBCTR9999_CHANGEMF PRIMARY KEY (
     OLD_BR_NO
    ,OLD_ACCOUNT_NO
));
COMMENT ON TABLE dbctr9999.CHANGEMF IS '読替マスタ';
COMMENT ON COLUMN dbctr9999.CHANGEMF.OLD_BR_NO IS '旧支店番号';
COMMENT ON COLUMN dbctr9999.CHANGEMF.OLD_ACCOUNT_NO IS '旧口座番号';
COMMENT ON COLUMN dbctr9999.CHANGEMF.NEW_BR_NO IS '新支店番号';
COMMENT ON COLUMN dbctr9999.CHANGEMF.NEW_ACCOUNT_NO IS '新口座番号';
COMMENT ON COLUMN dbctr9999.CHANGEMF.DESCRIPTION IS '備考';
exit;