DROP TABLE dbctr.SCAN_BATCH_CTL;
CREATE TABLE dbctr.SCAN_BATCH_CTL (
    INPUT_ROUTE number(1,0) NOT NULL,
    BATCH_FOLDER_NAME varchar2(20) NOT NULL,
    OC_BK_NO number(4,0) default -1  NOT NULL,
    OC_BR_NO number(4,0) default -1  NOT NULL,
    SCAN_BR_NO number(4,0) default -1  NOT NULL,
    SCAN_DATE number(8,0) default 0  NOT NULL,
    CLEARING_DATE number(8,0) default 0  NOT NULL,
    SCAN_COUNT number(6,0) default 0  NOT NULL,
    TOTAL_COUNT number(6,0) default 0  NOT NULL,
    TOTAL_AMOUNT number(18,0) default 0  NOT NULL,
    IMAGE_COUNT number(7,0) default 0  NOT NULL,
    STATUS number(1,0) default 0  NOT NULL,
    LOCK_TERM varchar2(20),
CONSTRAINT PK_DBCTR_SCAN_BATCH_CTL PRIMARY KEY (
     INPUT_ROUTE
    ,BATCH_FOLDER_NAME
));

COMMENT ON TABLE dbctr.SCAN_BATCH_CTL IS 'スキャンバッチ管理';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.INPUT_ROUTE IS '取込ルート:1:通常バッチルート 2:付帯バッチルート';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.BATCH_FOLDER_NAME IS 'バッチフォルダ名';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.OC_BK_NO IS '持出銀行コード';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.OC_BR_NO IS '持出支店コード';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.SCAN_BR_NO IS 'スキャン支店コード';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.SCAN_DATE IS 'スキャン日';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.CLEARING_DATE IS '交換希望日';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.SCAN_COUNT IS 'スキャン枚数';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.TOTAL_COUNT IS '合計枚数';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.TOTAL_AMOUNT IS '合計金額';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.IMAGE_COUNT IS 'イメージ数';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.STATUS IS '状態:1:処理待 2:処理中 3:処理済 5:保留 9:削除';
COMMENT ON COLUMN dbctr.SCAN_BATCH_CTL.LOCK_TERM IS 'ロック状態:イメージ取込のバッチ票画面を開いているコンピューター名称';
exit;