DROP TABLE dbctr.HOLIDAY;
CREATE TABLE dbctr.HOLIDAY (
    DAY number(8,0) NOT NULL,
    DESCRIPTION varchar2(50),
CONSTRAINT PK_DBCTR_HOLIDAY PRIMARY KEY (
     DAY
));
COMMENT ON TABLE dbctr.HOLIDAY IS 'ãxì˙É}ÉXÉ^';
COMMENT ON COLUMN dbctr.HOLIDAY.DAY IS 'ãxì˙';
COMMENT ON COLUMN dbctr.HOLIDAY.DESCRIPTION IS 'ê‡ñæ';
exit;