DROP TABLE dbctr9999.CTR_OCRCONF_PARAM;
CREATE TABLE dbctr9999.CTR_OCRCONF_PARAM (
    ITEM_NAME varchar2(30) NOT NULL,
    ITEM_TYPE varchar2(30) NOT NULL,
    CTR_MIN_CONF number(3,0) NOT NULL,
    CTR_MAX_CONF number(3,0) default 0 ,
    CONF number(3,0) default 0 ,
 CONSTRAINT PK_DBCTR9999_CTR_OCRCONF_PARAM PRIMARY KEY (
     ITEM_NAME
    ,ITEM_TYPE
    ,CTR_MIN_CONF
));
COMMENT ON TABLE dbctr9999.CTR_OCRCONF_PARAM IS '電子交換所OCR確信度パラメータ';
COMMENT ON COLUMN dbctr9999.CTR_OCRCONF_PARAM.ITEM_NAME IS '認識項目';
COMMENT ON COLUMN dbctr9999.CTR_OCRCONF_PARAM.ITEM_TYPE IS '認識タイプ';
COMMENT ON COLUMN dbctr9999.CTR_OCRCONF_PARAM.CTR_MIN_CONF IS '最小確信度';
COMMENT ON COLUMN dbctr9999.CTR_OCRCONF_PARAM.CTR_MAX_CONF IS '最大確信度';
COMMENT ON COLUMN dbctr9999.CTR_OCRCONF_PARAM.CONF IS '設定確信度';
exit;