DROP TABLE dbctr9999.HOSEIMODE_DSP_ITEM;
CREATE TABLE dbctr9999.HOSEIMODE_DSP_ITEM (
    GYM_ID NUMBER(3,0) NOT NULL,
    DSP_ID NUMBER(3,0) NOT NULL,
    HOSEI_ITEMMODE NUMBER(1,0) NOT NULL,
    ITEM_ID NUMBER(3,0) NOT NULL,
    NAME_POS_TOP NUMBER(5,0) default -1  NOT NULL,
    NAME_POS_LEFT NUMBER(5,0) default -1  NOT NULL,
    INPUT_POS_TOP NUMBER(5,0) default -1  NOT NULL,
    INPUT_POS_LEFT NUMBER(5,0) default -1  NOT NULL,
    INPUT_WIDTH NUMBER(5,0) default -1  NOT NULL,
    INPUT_HEIGHT NUMBER(5,0) default -1  NOT NULL,
    INPUT_SEQ NUMBER(2,0) default -1  NOT NULL,
 CONSTRAINT PK_DBCTR9999_HOSEIMODE_DSP_ITEM PRIMARY KEY (
     GYM_ID
    ,DSP_ID
    ,HOSEI_ITEMMODE
    ,ITEM_ID
));
COMMENT ON TABLE dbctr9999.HOSEIMODE_DSP_ITEM IS '補正モード画面項目定義';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.GYM_ID IS '業務番号:1：持出 2：持帰';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.HOSEI_ITEMMODE IS '補正項目モード:1：持帰銀行 2：交換希望日 3：金額 4：自行情報 5：交換尻';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.ITEM_ID IS '項目番号';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.NAME_POS_TOP IS '名称位置(TOP)';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.NAME_POS_LEFT IS '名称位置(LEFT)';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.INPUT_POS_TOP IS '入力位置(TOP)';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.INPUT_POS_LEFT IS '入力位置(LEFT)';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.INPUT_WIDTH IS '入力幅';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.INPUT_HEIGHT IS '入力高さ';
COMMENT ON COLUMN dbctr9999.HOSEIMODE_DSP_ITEM.INPUT_SEQ IS '入力順番:画面毎の項目入力順番';
exit;