DROP TABLE dbctr.BILLMF;
CREATE TABLE dbctr.BILLMF (
    BILL_CODE number(3,0) NOT NULL,
    KBN_NAME varchar2(10),
    STOCK_NAME varchar2(50),
    STOCK_RYAKU_NAME varchar2(50),
    DESCRIPTION varchar2(100),
 CONSTRAINT PK_DBCTR_BILLMF PRIMARY KEY (
     BILL_CODE
));
COMMENT ON TABLE dbctr.BILLMF IS '交換証券種類マスタ';
COMMENT ON COLUMN dbctr.BILLMF.BILL_CODE IS 'コード';
COMMENT ON COLUMN dbctr.BILLMF.KBN_NAME IS '区分名称';
COMMENT ON COLUMN dbctr.BILLMF.STOCK_NAME IS '交換証券種類';
COMMENT ON COLUMN dbctr.BILLMF.STOCK_RYAKU_NAME IS '交換証券種類略称';
COMMENT ON COLUMN dbctr.BILLMF.DESCRIPTION IS '備考';
exit;