DROP TABLE dbctr9999.SYURUIMF;
CREATE TABLE dbctr9999.SYURUIMF (
    SYURUI_CODE number(3,0) NOT NULL,
    SYURUI_NAME varchar2(50),
    INPUT_DSP_ID varchar2(100),
 CONSTRAINT PK_DBCTR9999_SYURUIMF PRIMARY KEY (
     SYURUI_CODE
));
COMMENT ON TABLE dbctr9999.SYURUIMF IS '種類マスタ';
COMMENT ON COLUMN dbctr9999.SYURUIMF.SYURUI_CODE IS '種類コード:999：その他レコードを必ず登録する';
COMMENT ON COLUMN dbctr9999.SYURUIMF.SYURUI_NAME IS '種別名称';
COMMENT ON COLUMN dbctr9999.SYURUIMF.INPUT_DSP_ID IS '入力可能画面番号:入力可能な画面番号をカンマ区切りで入力（空の場合はすべての画面番号で入力可能）';
exit;
