DROP TABLE dbctr.OPERATION_DATE;
CREATE TABLE dbctr.OPERATION_DATE (
    OPEDATE NUMBER(8,0) NOT NULL
);
COMMENT ON TABLE dbctr.OPERATION_DATE IS 'ˆ—“ú•t';
COMMENT ON COLUMN dbctr.OPERATION_DATE.OPEDATE IS '¼—ï“ú•t';
exit;
