DROP TABLE dbctr.BANKMF;
CREATE TABLE dbctr.BANKMF (
    BK_NO number(4,0) NOT NULL,
    BK_NAME_KANJI varchar2(30) NOT NULL,
    BK_NAME_KANA varchar2(30),
    KAMEI_FLG number(1,0) default 0  NOT NULL,
CONSTRAINT PK_DBCTR_BANKMF PRIMARY KEY (
     BK_NO
));
COMMENT ON TABLE dbctr.BANKMF IS '銀行マスタ';
COMMENT ON COLUMN dbctr.BANKMF.BK_NO IS '銀行コード';
COMMENT ON COLUMN dbctr.BANKMF.BK_NAME_KANJI IS '漢字名称';
COMMENT ON COLUMN dbctr.BANKMF.BK_NAME_KANA IS 'カナ名称';
COMMENT ON COLUMN dbctr.BANKMF.KAMEI_FLG IS '加盟フラグ:0：非加盟 1：加盟';
exit;