DROP TABLE dbctr9999.CHANGE_BILLMF;
CREATE TABLE dbctr9999.CHANGE_BILLMF (
    DSP_ID number(3,0) NOT NULL,
    BILL_CODE number(3,0) default 999  NOT NULL,
 CONSTRAINT PK_DBCTR9999_CHANGE_BILLMF PRIMARY KEY (
     DSP_ID
));
COMMENT ON TABLE dbctr9999.CHANGE_BILLMF IS '交換証券種類変換マスタ';
COMMENT ON COLUMN dbctr9999.CHANGE_BILLMF.DSP_ID IS '画面番号';
COMMENT ON COLUMN dbctr9999.CHANGE_BILLMF.BILL_CODE IS '証券種類コード';
exit;
